### ISSUE TITLE
Problème CSS

### ISSUE THREAD

**Issue by seydafall** [Github-Command-Unix/Test#2]
Les fichiers HTML et CSS ne sont pas liés. Est-ce que tu peux régler le soucis stp. Vérifie bien le nom du fichier CSS sur le fichier HTML.

**Comment by serineeazz** [comment]
Je n'ai pas réussi à régler ce problème. Es-ce que vous pouvez régler le soucis ?

**Comment by Antonin287** [comment]
Je m'en charge ;)

**Comment by Antonin287** [comment]
Done @serineeazz

**Comment by Antonin287** [comment]
je remodifie la ligne 10
